# Generated by Django 4.0.3 on 2022-04-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='boulette',
            field=models.BooleanField(default=True),
        ),
    ]
